import { bookContentUrl } from './api.js';
// Nomes históricos: renomeá-los faria downloads offline existentes desaparecerem.
const CACHE_NAME='biblioteca-digital-offline-v1',DB_NAME='biblioteca-digital-offline',STORE='items';
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function store(mode,action){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode),result=action(tx.objectStore(STORE));tx.oncomplete=()=>resolve(result?.result);tx.onerror=()=>reject(tx.error);});}
export async function listOfflineItems(){return(await store('readonly',object=>object.getAll()))||[];}
export async function isOffline(url){return Boolean(await(await caches.open(CACHE_NAME)).match(url));}
export async function downloadOffline(livro,{signal,onProgress}={}){const url=bookContentUrl(livro);if(!url)throw new Error('Arquivo indisponível para download.');const response=await fetch(url,{credentials:'include',signal});if(!response.ok)throw new Error(`Download falhou (${response.status}).`);const total=Number(response.headers.get('content-length')||livro.fileSize||0);let loaded=0;const cache=await caches.open(CACHE_NAME);if(response.body){const[monitor,content]=response.body.tee();const reader=monitor.getReader();const monitoring=(async()=>{while(true){const{done,value}=await reader.read();if(done)break;loaded+=value.byteLength;onProgress?.({loaded,total,progress:total?loaded/total:null});}})();const cached=new Response(content,{status:200,statusText:'OK',headers:response.headers});await Promise.all([monitoring,cache.put(url,cached)]);}else{await cache.put(url,response.clone());loaded=total;}const item={id:livro.id,workId:livro.workId||null,url,name:livro.nome,format:livro.formato,size:loaded||total,fingerprint:livro.fileFingerprint||'',downloadedAt:new Date().toISOString()};await store('readwrite',object=>object.put(item));return item;}
export async function removeOffline(item){const cache=await caches.open(CACHE_NAME);await cache.delete(item.url);await store('readwrite',object=>object.delete(item.id));}
export async function offlineQuota(){const estimate=await navigator.storage?.estimate?.();const items=await listOfflineItems();return{usage:Number(estimate?.usage||items.reduce((sum,item)=>sum+Number(item.size||0),0)),quota:Number(estimate?.quota||0),items};}
