import { useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Database, Languages, Palette, ShieldCheck, UserRound } from 'lucide-react';
import { apiFetch } from '../lib/api.js';
import { useLocale } from '../context/LocaleContext.jsx';

const steps = [
  { key: 'welcome', icon: ShieldCheck }, { key: 'language', icon: Languages },
  { key: 'server', icon: Database }, { key: 'admin', icon: ShieldCheck },
  { key: 'profile', icon: UserRound }, { key: 'preferences', icon: Palette },
  { key: 'finish', icon: Check }
];

export default function Setup({ onComplete }) {
  const { idioma, definirIdioma, t } = useLocale();
  const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [data, setData] = useState({ language: idioma, theme: 'system', server: { libraryName: 'Araru' }, admin: { username: 'admin', email: '', displayName: idioma === 'en' ? 'Administrator' : 'Administrador', password: '', confirmation: '' }, profile: { name: idioma === 'en' ? 'Main' : 'Principal', color: '#0891B2' }, preferences: { compactMode: false } });
  const patch = (section, value) => setData((current) => section ? ({ ...current, [section]: { ...current[section], ...value } }) : ({ ...current, ...value }));
  async function finish() { setError(''); if (data.admin.password !== data.admin.confirmation) return setError(t('setup.passwordMismatch')); setBusy(true); try { const response = await apiFetch('/setup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); definirIdioma(data.language); onComplete(); } catch (cause) { setError(cause.message || t('setup.failed')); } finally { setBusy(false); } }
  return <main className="access-home min-h-dvh bg-slate-950 px-4 py-6 text-slate-100 sm:px-8">
    <div className="mx-auto max-w-5xl"><header className="mb-8 flex items-center gap-3"><img src="/brand/araru-favicon.png" className="h-11 w-11 rounded-2xl" alt="" /><div><p className="font-semibold">Araru</p><p className="text-xs uppercase tracking-[.2em] text-slate-500">{t('setup.title')}</p></div></header>
      <div className="grid gap-6 lg:grid-cols-[240px_1fr]"><nav className="flex gap-2 overflow-x-auto lg:block lg:space-y-1" aria-label={t('setup.title')}>{steps.map((item,index)=><div key={item.key} className={`flex min-w-max items-center gap-3 rounded-xl px-3 py-3 text-sm ${index===step?'bg-cyan-300 text-slate-950':index<step?'text-cyan-300':'text-slate-500'}`}><item.icon className="h-4 w-4" />{t(`setup.${item.key}`)}</div>)}</nav>
        <section className="min-h-[480px] rounded-[2rem] border border-white/10 bg-white/[.06] p-6 shadow-2xl sm:p-10"><Step index={step} data={data} patch={patch} t={t} definirIdioma={definirIdioma} />{error&&<p role="alert" className="mt-5 text-sm text-rose-400">{error}</p>}<div className="mt-10 flex justify-between border-t border-white/10 pt-6"><button disabled={!step||busy} onClick={()=>setStep(step-1)} className="flex h-11 items-center gap-2 rounded-xl px-4 text-sm disabled:opacity-30"><ChevronLeft className="h-4 w-4"/>{t('setup.back')}</button>{step<steps.length-1?<button onClick={()=>setStep(step+1)} className="flex h-11 items-center gap-2 rounded-xl bg-cyan-300 px-5 text-sm font-semibold text-slate-950">{t('common.continue')}<ChevronRight className="h-4 w-4"/></button>:<button disabled={busy} onClick={finish} className="h-11 rounded-xl bg-cyan-300 px-5 text-sm font-semibold text-slate-950">{busy?t('setup.configuring'):t('setup.complete')}</button>}</div></section></div>
    </div></main>;
}

function Field({label,...props}){return <label className="block text-sm text-slate-300">{label}<input {...props} className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-black/20 px-4 text-white outline-none focus:border-cyan-300/60" /></label>}
function Step({index,data,patch,t,definirIdioma}) {
  if(index===0)return <><p className="text-sm font-medium uppercase tracking-[.2em] text-cyan-300">{t('setup.welcomeEyebrow')}</p><h1 className="mt-3 text-4xl font-semibold">{t('setup.welcomeTitle')}</h1><p className="mt-5 max-w-xl leading-7 text-slate-400">{t('setup.welcomeText')}</p></>;
  if(index===1)return <><h1 className="text-3xl font-semibold">{t('setup.languageTitle')}</h1><p className="mt-2 text-slate-400">{t('setup.languageHelp')}</p><select value={data.language} onChange={e=>{patch(null,{language:e.target.value});definirIdioma(e.target.value);}} className="mt-8 h-12 w-full rounded-xl bg-slate-900 px-4"><option value="pt-BR">Português (Brasil)</option><option value="en">English</option></select></>;
  if(index===2)return <><h1 className="text-3xl font-semibold">{t('setup.serverTitle')}</h1><div className="mt-8"><Field label={t('setup.libraryName')} value={data.server.libraryName} onChange={e=>patch('server',{libraryName:e.target.value})} required /></div></>;
  if(index===3)return <><h1 className="text-3xl font-semibold">{t('setup.adminTitle')}</h1><div className="mt-8 grid gap-4 sm:grid-cols-2"><Field label={t('auth.username')} value={data.admin.username} onChange={e=>patch('admin',{username:e.target.value})} required/><Field label={t('setup.displayName')} value={data.admin.displayName} onChange={e=>patch('admin',{displayName:e.target.value})}/><Field label={t('setup.email')} type="email" value={data.admin.email} onChange={e=>patch('admin',{email:e.target.value})}/><span/><Field label={t('auth.password')} type="password" minLength="8" value={data.admin.password} onChange={e=>patch('admin',{password:e.target.value})} required/><Field label={t('setup.confirmPassword')} type="password" value={data.admin.confirmation} onChange={e=>patch('admin',{confirmation:e.target.value})} required/></div></>;
  if(index===4)return <><h1 className="text-3xl font-semibold">{t('setup.profileTitle')}</h1><p className="mt-2 text-slate-400">{t('setup.profileHelp')}</p><div className="mt-8 grid gap-4 sm:grid-cols-[1fr_100px]"><Field label={t('setup.profileName')} value={data.profile.name} onChange={e=>patch('profile',{name:e.target.value})} required/><Field label={t('setup.color')} type="color" value={data.profile.color} onChange={e=>patch('profile',{color:e.target.value})}/></div></>;
  if(index===5)return <><h1 className="text-3xl font-semibold">{t('setup.preferencesTitle')}</h1><label className="mt-8 flex items-center gap-3 rounded-xl border border-white/10 p-4"><input type="checkbox" checked={data.preferences.compactMode} onChange={e=>patch('preferences',{compactMode:e.target.checked})}/>{t('setup.compactMode')}</label><label className="mt-4 block text-sm">{t('setup.theme')}<select value={data.theme} onChange={e=>patch(null,{theme:e.target.value})} className="mt-2 h-12 w-full rounded-xl bg-slate-900 px-4"><option value="system">{t('common.system')}</option><option value="dark">{t('common.dark')}</option><option value="light">{t('common.light')}</option></select></label></>;
  return <><Check className="h-12 w-12 rounded-full bg-cyan-300 p-3 text-slate-950"/><h1 className="mt-6 text-3xl font-semibold">{t('setup.ready')}</h1><p className="mt-3 text-slate-400">{t('setup.review',{library:data.server.libraryName,admin:data.admin.username,profile:data.profile.name})}</p></>;
}
