import { useEffect, useState } from 'react';
import { api, apiErrorMessage } from '../lib/api.js';
import { useLocale } from '../context/LocaleContext.jsx';

export default function CoverCacheControls() {
  const { t, idioma } = useLocale(); const copy = idioma === 'en' ? { title: 'Cover cache', help: 'Derived covers are generated in background and shared by all providers.', generate: 'Generate missing', ready: 'Ready', missing: 'Missing', processing: 'Processing', failed: 'Failed', total: 'Total', retry: 'Retry failed', rebuild: 'Rebuild cache', confirm: 'Rebuild all cached covers? This may consume CPU, disk, and bandwidth.', started: 'Cover generation queued.' } : { title: 'Cache de capas', help: 'As capas derivadas são geradas em segundo plano e funcionam com todos os providers.', generate: 'Gerar ausentes', ready: 'Prontas', missing: 'Ausentes', processing: 'Processando', failed: 'Com erro', total: 'Total', retry: 'Tentar erros', rebuild: 'Recriar cache', confirm: 'Recriar todas as capas em cache? Isso pode consumir CPU, disco e banda.', started: 'Geração de capas enfileirada.' }; const [status, setStatus] = useState(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { try { const { data } = await api.get('/admin/covers/status'); setStatus(data.data || data); } catch (error) { setMessage(apiErrorMessage(error)); } }
  useEffect(() => { load(); }, []);
  async function run(path, body) { if (busy) return; setBusy(true); setMessage(''); try { const { data } = await api.post(path, body); setMessage(copy.started + (data?.data?.queued ? ` (${data.data.queued})` : '')); await load(); } catch (error) { setMessage(apiErrorMessage(error)); } finally { setBusy(false); } }
  return <section className="rounded-xl border border-[var(--app-border)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{copy.title}</h2><p className="mt-1 text-sm text-[var(--text-muted)]">{copy.help}</p></div><button type="button" disabled={busy} onClick={() => run('/admin/covers/generate-missing')} className="min-h-10 rounded-xl bg-[var(--brand-primary)] px-4 text-sm font-semibold text-[var(--accent-foreground)] disabled:opacity-50">{copy.generate}</button></div><div className="mt-5 grid grid-cols-2 gap-x-6 sm:grid-cols-5">{[['ready','ready'],['missing','missing'],['processing','processing'],['failed','failed'],['total','total']].map(([key, label]) => <div key={key} className="border-t border-[var(--app-border)] py-3"><p className="text-xs text-[var(--text-muted)]">{copy[label]}</p><strong className="text-lg">{status?.[key] ?? '—'}</strong></div>)}</div><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => run('/admin/covers/retry-failed')} className="min-h-10 rounded-xl border border-[var(--app-border)] px-3 text-sm disabled:opacity-50">{copy.retry}</button><button type="button" disabled={busy} onClick={() => { if (window.confirm(copy.confirm)) run('/admin/covers/rebuild', { mode: 'force', confirmed: true }); }} className="min-h-10 rounded-xl border border-[var(--app-border)] px-3 text-sm disabled:opacity-50">{copy.rebuild}</button></div>{message && <p role="status" className="mt-3 text-sm text-[var(--text-muted)]">{message}</p>}</section>;
}
