import { AlertCircle, CheckCircle2, ChevronLeft, ChevronRight, Circle, Clock3, LoaderCircle, Play, RefreshCw, Search, Trash2, XCircle } from 'lucide-react';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { api, apiErrorMessage } from '../lib/api.js';
import AdminTabs from '../features/admin/components/AdminTabs.jsx';

const labels = { queued: 'Na fila', running: 'Em execução', completed: 'Concluído', failed: 'Falhou', cancelled: 'Cancelado' };
const tabs = [['overview', 'Visão geral'], ['executions', 'Execuções'], ['schedules', 'Agendamentos'], ['types', 'Tipos de job']];
const get = (path, options) => api.get(path, options).then(({ data }) => data.data || data);
const icons = { queued: Circle, running: LoaderCircle, completed: CheckCircle2, failed: AlertCircle, cancelled: XCircle };
const friendly = (type = '') => type.split(/[-_]/).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');
const date = (value) => value ? new Date(value).toLocaleString([], { dateStyle: 'short', timeStyle: 'short' }) : '—';
const elapsed = (job) => job.startedAt ? `${((new Date(job.completedAt || Date.now()) - new Date(job.startedAt)) / 1000).toFixed(1)}s` : '—';
function Status({ value }) { const Icon = icons[value] || Circle; return <span className={`inline-flex items-center gap-1.5 text-xs font-medium ${value === 'failed' ? 'text-[var(--danger)]' : value === 'running' ? 'text-[var(--info)]' : 'text-[var(--text-muted)]'}`}><Icon className={`h-3.5 w-3.5 ${value === 'running' ? 'animate-spin' : ''}`} />{labels[value] || value}</span>; }
function Metric({ label, value, status, onClick }) { return <button type="button" onClick={onClick} className="rounded-xl border border-[var(--app-border)] bg-[var(--app-panel)] p-4 text-left transition hover:border-[var(--border-strong)]"><span className="text-xs text-[var(--text-muted)]">{label}</span><strong className="mt-1 block text-2xl">{value ?? 0}</strong><Status value={status} /></button>; }
function Pager({ page, pages, total, onChange }) { return <div className="mt-3 flex items-center justify-between gap-3 text-xs text-[var(--text-muted)]"><span>{total} registros · Página {page} de {pages}</span><span className="flex gap-1"><button type="button" disabled={page <= 1} onClick={() => onChange(page - 1)} className="grid h-8 w-8 place-items-center rounded-md border border-[var(--app-border)] disabled:opacity-35" aria-label="Página anterior"><ChevronLeft className="h-4 w-4" /></button><button type="button" disabled={page >= pages} onClick={() => onChange(page + 1)} className="grid h-8 w-8 place-items-center rounded-md border border-[var(--app-border)] disabled:opacity-35" aria-label="Próxima página"><ChevronRight className="h-4 w-4" /></button></span></div>; }
function Detail({ id, close }) { const { data } = useQuery({ queryKey: ['admin', 'jobs', 'detail', id], queryFn: () => get(`/admin/jobs/${id}`) }); return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 p-3 sm:items-center"><article role="dialog" aria-modal="true" className="max-h-[88vh] w-full max-w-2xl overflow-auto rounded-2xl border border-[var(--app-border)] bg-[var(--app-panel)] p-5 shadow-2xl"><div className="flex justify-between gap-4"><div><p className="text-xs uppercase tracking-[.14em] text-[var(--text-muted)]">Execução</p><h2 className="mt-1 text-lg font-semibold">{data ? friendly(data.type) : 'Carregando…'}</h2></div><button type="button" onClick={close} aria-label="Fechar detalhes"><XCircle /></button></div>{data && <><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><p>Status<br /><Status value={data.status} /></p><p>Worker<br />{data.workerId || 'Aguardando worker'}</p><p>Criado em<br />{date(data.createdAt)}</p><p>Duração<br />{elapsed(data)}</p><p>Tentativas<br />{data.attempts}/{data.maxAttempts}</p></div>{data.error && <p className="mt-5 rounded-lg bg-red-500/10 p-3 text-sm text-[var(--danger)]">{data.error}</p>}<h3 className="mt-6 text-sm font-semibold">Logs da execução</h3>{data.logs?.length ? <div className="mt-3 divide-y divide-[var(--app-border)] rounded-lg border border-[var(--app-border)]">{data.logs.map((log) => <div key={log.id} className="p-3 text-sm"><span className="text-xs text-[var(--text-muted)]">{log.level} · {date(log.createdAt)}</span><p className="mt-1">{log.message}</p></div>)}</div> : <p className="mt-3 text-sm text-[var(--text-muted)]">Nenhum log registrado.</p>}</>}</article></div>; }

export default function OperationsPanel() {
  const client = useQueryClient(); const [params, setParams] = useSearchParams(); const [recentPage, setRecentPage] = useState(1); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [type, setType] = useState(''); const [selected, setSelected] = useState(null); const tab = tabs.some(([key]) => key === params.get('tab')) ? params.get('tab') : 'overview'; const status = params.get('status') || '';
  const setTab = (next) => { setParams(next === 'overview' ? {} : { tab: next }); setPage(1); };
  const center = useQuery({ queryKey: ['admin', 'jobs', 'center', recentPage], queryFn: () => get('/admin/jobs/center', { params: { recentPage, recentPageSize: 5 } }), refetchInterval: 5000 });
  const executions = useQuery({ queryKey: ['admin', 'jobs', { page, type, search, status }], queryFn: () => get('/admin/jobs', { params: { page, pageSize: 12, ...(type && { type }), ...(status && { status }), ...(search.trim() && { search: search.trim() }) } }), refetchInterval: 5000, enabled: tab === 'executions' });
  const definitions = useQuery({ queryKey: ['admin', 'jobs', 'definitions'], queryFn: () => get('/admin/jobs/definitions'), enabled: tab === 'types' || tab === 'schedules' }); const schedules = useQuery({ queryKey: ['admin', 'jobs', 'schedules'], queryFn: () => get('/admin/jobs/schedules'), enabled: tab === 'schedules' || tab === 'overview' });
  const action = useMutation({ mutationFn: ({ id, operation }) => api.post(`/admin/jobs/${id}/${operation}`), onSuccess: () => { client.invalidateQueries({ queryKey: ['admin', 'jobs'] }); toast.success('Job atualizado.'); }, onError: (error) => toast.error(apiErrorMessage(error)) }); const run = useMutation({ mutationFn: (jobType) => api.post('/admin/jobs/run', { type: jobType }), onSuccess: () => { client.invalidateQueries({ queryKey: ['admin', 'jobs'] }); toast.success('Job enfileirado.'); }, onError: (error) => toast.error(apiErrorMessage(error)) }); const remove = useMutation({ mutationFn: (id) => api.delete(`/admin/jobs/schedules/${id}`), onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'jobs', 'schedules'] }), onError: (error) => toast.error(apiErrorMessage(error)) }); const saveSchedule = useMutation({ mutationFn: (item) => api.post('/admin/jobs/schedules', item), onSuccess: () => { client.invalidateQueries({ queryKey: ['admin', 'jobs', 'schedules'] }); toast.success('Agendamento atualizado.'); }, onError: (error) => toast.error(apiErrorMessage(error)) });
  const overview = center.data || { metrics: {}, recent: [], upcoming: [], recentPagination: { page: 1, pages: 1, total: 0 } }; const data = executions.data || { items: [], pagination: {}, types: [] }; const pagination = data.pagination || { page: 1, pages: 1, total: 0 }; const scheduleItems = schedules.data || [];
  const failed = () => { setParams({ tab: 'executions', status: 'failed' }); setPage(1); };
  return <section className="space-y-6"><AdminTabs tabs={tabs.map(([key, text]) => [key, <>{text}{key === 'executions' && center.data && <span className="ml-2 text-xs">{Object.values(overview.metrics).reduce((sum, value) => sum + Number(value || 0), 0)}</span>}{key === 'schedules' && scheduleItems.length > 0 && <span className="ml-2 text-xs">{scheduleItems.length}</span>}</>])} />
    {tab === 'overview' && <div className="space-y-6"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Em execução" value={overview.metrics.running} status="running" onClick={() => setTab('executions')} /><Metric label="Na fila" value={overview.metrics.queued} status="queued" onClick={() => setTab('executions')} /><Metric label="Falharam" value={overview.metrics.failed} status="failed" onClick={failed} /><Metric label="Concluídos" value={overview.metrics.completed} status="completed" onClick={() => setTab('executions')} /></div><div className="grid gap-6 lg:grid-cols-2"><section><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Atividade recente</h2><button type="button" onClick={() => client.invalidateQueries({ queryKey: ['admin', 'jobs', 'center'] })} aria-label="Atualizar atividade" className="text-[var(--text-muted)]"><RefreshCw className="h-4 w-4" /></button></div>{overview.recent?.length ? <div className="mt-3 divide-y divide-[var(--app-border)] border-y border-[var(--app-border)]">{overview.recent.map((job) => <button type="button" key={job.id} onClick={() => setSelected(job.id)} className="flex w-full items-center gap-3 py-3 text-left hover:bg-[var(--app-panel)]"><span className="min-w-0 flex-1 truncate text-sm font-medium">{friendly(job.type)}</span><Status value={job.status} /><span className="hidden w-28 text-right text-xs text-[var(--text-muted)] sm:block">{date(job.createdAt)}</span></button>)}</div> : <p className="mt-3 border-y border-[var(--app-border)] py-4 text-sm text-[var(--text-muted)]">Nenhuma execução registrada.</p>}<Pager {...overview.recentPagination} onChange={setRecentPage} /></section><section><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Próximas execuções</h2><button type="button" onClick={() => setTab('schedules')} className="text-xs text-[var(--link)]">Gerenciar</button></div>{overview.upcoming?.length ? <div className="mt-3 divide-y divide-[var(--app-border)] border-y border-[var(--app-border)]">{overview.upcoming.map((item) => <div key={item.id} className="flex items-center gap-3 py-3"><Clock3 className="h-4 w-4 text-[var(--text-muted)]" /><div><p className="text-sm font-medium">{item.name || friendly(item.jobType)}</p><p className="text-xs text-[var(--text-muted)]">{item.nextRunAt ? date(item.nextRunAt) : item.cron}</p></div></div>)}</div> : <p className="mt-3 border-y border-[var(--app-border)] py-4 text-sm text-[var(--text-muted)]">Nenhuma execução agendada.</p>}</section></div></div>}
    {tab === 'executions' && <Executions data={data} pagination={pagination} page={page} setPage={setPage} search={search} setSearch={setSearch} type={type} setType={setType} status={status} select={setSelected} action={action} />}
    {tab === 'types' && <div className="grid gap-3 md:grid-cols-2">{(definitions.data || []).map((item) => <article key={item.type} className="rounded-xl border border-[var(--app-border)] bg-[var(--app-panel)] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">{item.name || friendly(item.type)}</h2><p className="mt-1 text-sm text-[var(--text-muted)]">{item.description || item.type}</p><p className="mt-3 text-xs text-[var(--text-muted)]">{item.type} · timeout {item.defaultTimeoutMs}ms</p></div><button type="button" onClick={() => run.mutate(item.type)} disabled={!item.registered || run.isPending} aria-label={`Executar ${item.name || item.type}`} className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--app-border)]"><Play className="h-4 w-4" /></button></div></article>)}</div>}
    {tab === 'schedules' && <Schedules schedules={scheduleItems} definitions={definitions.data || []} save={(item) => saveSchedule.mutate(item)} remove={(id) => remove.mutate(id)} />}{selected && <Detail id={selected} close={() => setSelected(null)} />}
  </section>;
}

function Executions({ data, pagination, page, setPage, search, setSearch, type, setType, status, select, action }) { const rows = data.items || []; return <div className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row"><label className="flex min-h-10 flex-1 items-center gap-2 rounded-lg border border-[var(--app-border)] px-3"><Search className="h-4 w-4 text-[var(--text-muted)]" /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="Pesquisar jobs e erros" /></label><select value={type} onChange={(event) => { setType(event.target.value); setPage(1); }} className="min-h-10 rounded-lg border border-[var(--app-border)] bg-[var(--app-panel)] px-3 text-sm"><option value="">Todos os tipos</option>{(data.types || []).map((item) => <option key={item} value={item}>{friendly(item)}</option>)}</select>{status && <button type="button" onClick={() => window.history.replaceState({}, '', '/admin/jobs?tab=executions')} className="text-xs text-[var(--link)]">Limpar filtro</button>}</div><div className="divide-y divide-[var(--app-border)] rounded-lg border border-[var(--app-border)]">{rows.map((job) => <article key={job.id} className="grid gap-3 px-4 py-3 md:grid-cols-[1.5fr_1fr_1.2fr_.7fr_1fr_auto] md:items-center"><button type="button" onClick={() => select(job.id)} className="truncate text-left text-sm font-medium hover:text-[var(--link)]">{friendly(job.type)}</button><Status value={job.status} /><span className="text-xs text-[var(--text-muted)]">{date(job.startedAt || job.createdAt)}</span><span className="text-xs text-[var(--text-muted)]">{elapsed(job)}</span><span className="text-xs text-[var(--text-muted)]">{job.attempts}/{job.maxAttempts} · {job.workerId || '—'}</span><div>{['queued', 'running'].includes(job.status) && <button type="button" onClick={() => action.mutate({ id: job.id, operation: 'cancel' })} className="text-xs">Cancelar</button>}{['failed', 'cancelled'].includes(job.status) && <button type="button" onClick={() => action.mutate({ id: job.id, operation: 'retry' })} className="text-xs">Retry</button>}</div></article>)}{!rows.length && <p className="p-5 text-sm text-[var(--text-muted)]">Nenhuma execução encontrada.</p>}</div><Pager page={pagination.page || page} pages={Math.max(1, pagination.pages || 1)} total={pagination.total || 0} onChange={setPage} /></div>; }

function Schedules({ schedules, definitions, save, remove }) { const [draft, setDraft] = useState({ name: '', jobType: definitions[0]?.type || 'catalog-reconcile', cron: '0 */6 * * *', enabled: true }); const update = (field, value) => setDraft((current) => ({ ...current, [field]: value })); return <div className="space-y-4"><form onSubmit={(event) => { event.preventDefault(); save({ ...draft, name: draft.name || draft.jobType }); }} className="grid gap-3 rounded-xl border border-[var(--app-border)] bg-[var(--app-panel)] p-4 md:grid-cols-[1.2fr_1fr_1.3fr_auto]"><input required value={draft.name} onChange={(event) => update('name', event.target.value)} placeholder="Nome do agendamento" className="min-h-10 rounded-lg border border-[var(--app-border)] bg-transparent px-3 text-sm" /><select value={draft.jobType} onChange={(event) => update('jobType', event.target.value)} className="min-h-10 rounded-lg border border-[var(--app-border)] bg-transparent px-3 text-sm">{definitions.map((item) => <option key={item.type} value={item.type}>{item.name || item.type}</option>)}</select><input required pattern="^([*0-9,/-]+\s+){4}[*0-9,/-]+$" value={draft.cron} onChange={(event) => update('cron', event.target.value)} placeholder="Cron: 0 */6 * * *" className="min-h-10 rounded-lg border border-[var(--app-border)] bg-transparent px-3 text-sm" /><button className="min-h-10 rounded-lg bg-[var(--brand-primary)] px-4 text-sm font-semibold text-[var(--accent-foreground)]">Criar</button></form>{schedules.map((item) => <article key={item.id} className="flex flex-wrap items-center gap-3 border-b border-[var(--app-border)] py-3"><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold">{item.name}</h2><p className="mt-1 text-xs text-[var(--text-muted)]">{friendly(item.jobType)} · {item.cron} · {item.enabled ? 'Ativo' : 'Inativo'}</p><p className="mt-1 text-xs text-[var(--text-muted)]">Próxima: {item.nextRunAt ? date(item.nextRunAt) : 'Não calculada'}</p></div><button type="button" onClick={() => save({ ...item, enabled: !item.enabled })} className="min-h-9 rounded-lg border border-[var(--app-border)] px-3 text-xs">{item.enabled ? 'Pausar' : 'Ativar'}</button><button type="button" onClick={() => remove(item.id)} aria-label={`Remover ${item.name}`} className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--app-border)] text-[var(--danger)]"><Trash2 className="h-4 w-4" /></button></article>)}{!schedules.length && <p className="py-5 text-sm text-[var(--text-muted)]">Nenhum agendamento configurado.</p>}</div>; }
