import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { api, fetchJson } from '../lib/api.js';

export default function ReaderPreferences() {
  const client=useQueryClient(); const query=useQuery({queryKey:['preferences'],queryFn:({signal})=>fetchJson('/preferences',{signal})});
  const save=useMutation({mutationFn:(data)=>api.put('/preferences',data),onMutate:async(data)=>{await client.cancelQueries({queryKey:['preferences']});const old=client.getQueryData(['preferences']);client.setQueryData(['preferences'],{data});return{old};},onError:(_e,_v,ctx)=>{client.setQueryData(['preferences'],ctx.old);toast.error('Preferências não foram salvas.');},onSettled:()=>client.invalidateQueries({queryKey:['preferences']})});
  const prefs=query.data?.data; if(!prefs)return <p className="text-xs text-slate-500">Carregando preferências…</p>;
  const update=(field,value)=>save.mutate({...prefs,[field]:value});
  return <section className="space-y-3 rounded-2xl border border-slate-200 p-3 dark:border-slate-800"><div><h3 className="text-sm font-semibold">Preferências de leitura</h3><p className="mt-1 text-xs text-slate-500">Aplicadas ao perfil; ajustes do livro têm prioridade.</p></div><label className="flex items-center justify-between gap-3 text-sm"><span>Modo padrão</span><select value={prefs.readingMode} onChange={(e)=>update('readingMode',e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-transparent px-3 dark:border-slate-700"><option value="page">Página</option><option value="continuous">Contínuo</option><option value="webtoon">Webtoon</option></select></label><label className="flex items-center justify-between gap-3 text-sm"><span>Tema</span><select value={prefs.theme} onChange={(e)=>update('theme',e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-transparent px-3 dark:border-slate-700"><option value="system">Sistema</option><option value="claro">Claro</option><option value="sepia">Sépia</option><option value="escuro">Escuro</option></select></label><label className="flex items-center justify-between gap-3 text-sm"><span>Formato de texto</span><select value={prefs.preferredFormats?.reflowable?.[0]||'epub'} onChange={(e)=>update('preferredFormats',{...prefs.preferredFormats,reflowable:[e.target.value,...['epub','mobi','pdf'].filter(x=>x!==e.target.value)]})} className="h-11 rounded-xl border border-slate-200 bg-transparent px-3 dark:border-slate-700"><option value="epub">EPUB</option><option value="mobi">MOBI</option><option value="pdf">PDF</option></select></label></section>;
}
