import { useEffect, useState } from 'react';
import { api, apiFetch } from '../../../lib/api.js';
import { useLocale } from '../../../context/LocaleContext.jsx';
import BackupControls from '../../../components/BackupControls.jsx';
import DuplicateReview from '../../../components/DuplicateReview.jsx';
import ImportExportControls from '../../../components/ImportExportControls.jsx';
import OperationsPanel from '../../../components/OperationsPanel.jsx';
import RevisarMetadados from '../../../components/RevisarMetadados.jsx';
import { AdminPage, StatusLine } from '../components/AdminPrimitives.jsx';

function useEndpoint(path){const[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{api.get(path).then(response=>setData(response.data.data||response.data)).catch(cause=>setError(cause.response?.data?.message||cause.message));},[path]);return{data,error};}
export function OverviewPage(){const{t}=useLocale(),{data,error}=useEndpoint('/admin/overview');return <AdminPage title={t('admin.sections.overview')} description={t('admin.descriptions.overview')}>{error&&<p role="alert" className="text-rose-500">{error}</p>}{!data?<p className="text-sm text-slate-500">{t('common.loading')}</p>:<div className="grid gap-x-10 md:grid-cols-2"><StatusLine label={t('admin.metrics.server')} value={data.server.status} tone="good"/><StatusLine label={t('admin.metrics.users')} value={data.users}/><StatusLine label={t('admin.metrics.profiles')} value={data.profiles}/><StatusLine label={t('admin.metrics.libraries')} value={data.libraries}/><StatusLine label="PostgreSQL" value={data.database.healthy?'OK':t('admin.unavailable')} tone={data.database.healthy?'good':'default'}/><StatusLine label="Redis" value={data.redis.healthy?'OK':t('admin.unavailable')} tone={data.redis.healthy?'good':'default'}/><StatusLine label={t('admin.metrics.jobs')} value={(data.jobs.running||0)+Number(data.jobs.queued||0)}/><StatusLine label={t('admin.metrics.version')} value={data.server.version}/></div>}</AdminPage>}
export function LibrariesPage(){const{t}=useLocale(),{data}=useEndpoint('/admin/overview'),[status,setStatus]=useState('');async function sync(){setStatus(t('admin.feedback.saving'));const response=await apiFetch('/categorias/sincronizar',{method:'POST'});setStatus(response.ok?t('admin.feedback.started'):t('admin.feedback.failed'));}return <AdminPage title={t('admin.sections.libraries')} description={t('admin.descriptions.libraries')}><StatusLine label={t('admin.metrics.books')} value={data?.catalog?.total??'—'}/><StatusLine label={t('admin.metrics.source')} value={data?.catalog?.sources?.local??'Local'}/><button onClick={sync} className="mt-6 min-h-11 rounded-xl bg-[var(--brand-primary)] px-5 text-sm font-semibold text-white">{t('admin.scanLibrary')}</button>{status&&<p role="status" className="mt-3 text-sm text-slate-500">{status}</p>}</AdminPage>}
export function StoragePage(){const{t}=useLocale(),{data,error}=useEndpoint('/health/details');return <AdminPage title={t('admin.sections.storage')} description={t('admin.descriptions.storage')}>{error&&<p className="text-rose-500">{error}</p>}<StatusLine label={t('admin.localLibrary')} value={data?.localLibraryDir||'—'}/><StatusLine label="PostgreSQL" value={data?.database?.healthy?'OK':'—'} tone={data?.database?.healthy?'good':'default'}/><StatusLine label="Redis" value={data?.redis?.healthy?'OK':'—'} tone={data?.redis?.healthy?'good':'default'}/><StatusLine label="Google Drive" value={data?.googleDriveEnabled?(data.googleDriveAuthenticated?t('common.active'):t('admin.notConnected')):t('common.inactive')}/></AdminPage>}
export function MetadataPage(){const{t}=useLocale();return <AdminPage title={t('admin.sections.metadata')} description={t('admin.descriptions.metadata')}><div className="grid gap-5 xl:grid-cols-2"><RevisarMetadados/><DuplicateReview/><ImportExportControls/></div></AdminPage>}
export function JobsPage(){const{t}=useLocale();return <AdminPage title={t('admin.sections.jobs')} description={t('admin.descriptions.jobs')}><OperationsPanel/></AdminPage>}
export function BackupPage(){const{t}=useLocale();return <AdminPage title={t('admin.sections.backup')} description={t('admin.descriptions.backup')}><div className="max-w-xl"><BackupControls/></div></AdminPage>}
export function SecurityPage(){const{t}=useLocale(),{data}=useEndpoint('/admin/audit?limit=30');return <AdminPage title={t('admin.sections.security')} description={t('admin.descriptions.security')}><div className="divide-y divide-[var(--app-border)]">{(data||[]).map(item=><article key={item.id} className="py-4"><p className="text-sm font-medium">{item.action}</p><p className="mt-1 text-xs text-slate-500">{item.actor||t('admin.systemActor')} · {new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.createdAt))}</p></article>)}{data&&!data.length&&<p className="text-sm text-slate-500">{t('admin.noAudit')}</p>}</div></AdminPage>}
export function SystemPage(){const{t}=useLocale(),{data,error}=useEndpoint('/health/details');return <AdminPage title={t('admin.sections.system')} description={t('admin.descriptions.system')}>{error&&<p className="text-rose-500">{error}</p>}<StatusLine label={t('admin.metrics.server')} value={data?.status||'—'} tone={data?.status==='ok'?'good':'default'}/><StatusLine label={t('admin.metrics.uptime')} value={data?.runtime?`${Math.floor(data.runtime.uptimeSeconds/60)} min`:'—'}/><StatusLine label="PostgreSQL" value={data?.database?.healthy?'OK':'—'}/><StatusLine label="Redis" value={data?.redis?.healthy?'OK':'—'}/><StatusLine label={t('admin.metrics.watcher')} value={data?.watcher?.running?t('common.active'):t('common.inactive')}/></AdminPage>}
