import { useEffect, useState } from 'react';
import { api, apiErrorMessage } from '../../../lib/api.js';
import { useLocale } from '../../../context/LocaleContext.jsx';
import { useTema } from '../../../context/TemaContext.js';
import { AdminPage, Field, inputClass, SettingsGroup } from '../components/AdminPrimitives.jsx';

function useSettings(){const{idioma}=useLocale(),{tema}=useTema(),[settings,setSettings]=useState({libraryName:'Araru',language:idioma,theme:tema,timezone:'America/Sao_Paulo',dateFormat:'locale',allowRegistration:false}),[status,setStatus]=useState('');useEffect(()=>{api.get('/settings/general').then(({data})=>setSettings(current=>({...current,...data.data}))).catch(e=>setStatus(apiErrorMessage(e)));},[]);const save=async()=>{setStatus('saving');try{await api.put('/settings/general',settings);setStatus('saved');setTimeout(()=>window.location.reload(),450);}catch(e){setStatus(apiErrorMessage(e));}};return{settings,setSettings,status,save};}
function SaveButton({status,onClick,t}){return <button type="button" disabled={status==='saving'} onClick={onClick} className="min-h-11 rounded-xl bg-[var(--brand-primary)] px-5 text-sm font-semibold text-white disabled:opacity-50">{status==='saving'?t('admin.feedback.saving'):t('common.save')}</button>}
export function GeneralPage(){const{t}=useLocale(),form=useSettings();return <AdminPage title={t('admin.sections.general')} description={t('admin.descriptions.general')} actions={<SaveButton {...form} onClick={form.save} t={t}/>}><SettingsGroup title={t('admin.serverIdentity')} description={t('admin.descriptions.identity')}><Field label={t('admin.libraryName')} help={t('admin.help.libraryName')}><input className={inputClass} value={form.settings.libraryName||''} maxLength={80} onChange={e=>form.setSettings({...form.settings,libraryName:e.target.value})}/></Field></SettingsGroup><SettingsGroup title={t('admin.regional')} description={t('admin.descriptions.regional')}><Field label={t('admin.timezone')} help={t('admin.help.timezone')}><input className={inputClass} value={form.settings.timezone||''} onChange={e=>form.setSettings({...form.settings,timezone:e.target.value})}/></Field><Field label={t('admin.dateFormat')} help={t('admin.help.dateFormat')}><select className={inputClass} value={form.settings.dateFormat||'locale'} onChange={e=>form.setSettings({...form.settings,dateFormat:e.target.value})}><option value="locale">{t('admin.dateFormats.locale')}</option><option value="iso">ISO 8601</option></select></Field></SettingsGroup>{form.status&&form.status!=='saving'&&<p role="status" className="text-sm text-slate-500">{form.status==='saved'?t('admin.saved'):form.status}</p>}</AdminPage>}
export function AppearancePage(){const{t}=useLocale(),form=useSettings();return <AdminPage title={t('admin.sections.appearance')} description={t('admin.descriptions.appearance')} actions={<SaveButton {...form} onClick={form.save} t={t}/>}><SettingsGroup title={t('admin.interface')} description={t('admin.descriptions.interface')}><Field label={t('admin.theme')} help={t('admin.help.theme')}><select className={inputClass} value={form.settings.theme||'system'} onChange={e=>form.setSettings({...form.settings,theme:e.target.value})}><option value="system">{t('common.system')}</option><option value="dark">{t('common.dark')}</option><option value="light">{t('common.light')}</option></select></Field><Field label={t('admin.language')} help={t('admin.help.language')}><select className={inputClass} value={form.settings.language||'pt-BR'} onChange={e=>form.setSettings({...form.settings,language:e.target.value})}><option value="pt-BR">Português (Brasil)</option><option value="en">English</option></select></Field></SettingsGroup></AdminPage>}
