import { Pencil, Plus, Trash2, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api, apiErrorMessage } from '../../../lib/api.js';
import { Dialog, DialogContent } from '../../../components/ui/dialog';
import { AdminPage, inputClass } from '../components/AdminPrimitives.jsx';
import { AdminDataGrid, StatusBadge } from '../components/AdminDataGrid.jsx';

const blank = { name: '', description: '', permissions: [], libraryAccess: [] };
const actionLabels = { read: 'Visualizar', create: 'Criar', update: 'Editar', delete: 'Excluir', manage: 'Gerenciar', execute: 'Executar', restore: 'Restaurar' };
const groupLabels = { general: 'Configurações', users: 'Usuários', roles: 'Funções e permissões', libraries: 'Bibliotecas', metadata: 'Metadados', jobs: 'Jobs', backup: 'Backup', security: 'Segurança', system: 'Sistema' };
function PermissionGroups({ groups, selected, onToggle }) { return <div className="mt-2"><div className="mb-3 flex items-center justify-between gap-3"><p className="text-xs text-[var(--text-muted)]">Escolha apenas o acesso necessário para esta função.</p><span className="text-xs font-medium text-[var(--text-muted)]">{selected.length} selecionada(s)</span></div><div className="grid gap-3 sm:grid-cols-2">{groups.map((group) => { const groupPermissions = group.permissions || []; const selectedCount = groupPermissions.filter((permission) => selected.includes(permission)).length; const allSelected = groupPermissions.length > 0 && selectedCount === groupPermissions.length; return <fieldset key={group.id} className="rounded-xl border border-[var(--app-border)] bg-[var(--app-bg)] p-3"><div className="flex items-center justify-between gap-3 border-b border-[var(--app-border)] pb-2"><legend className="text-sm font-semibold">{groupLabels[group.id] || group.label || group.id}</legend><label className="flex cursor-pointer items-center gap-1.5 text-[11px] text-[var(--text-muted)]"><input type="checkbox" checked={allSelected} ref={(element) => { if (element) element.indeterminate = selectedCount > 0 && !allSelected; }} onChange={() => groupPermissions.forEach((permission) => { if (allSelected === selected.includes(permission)) onToggle(permission); })} />{selectedCount}/{groupPermissions.length}</label></div><div className="mt-2 grid gap-1">{groupPermissions.map((permission) => { const action = permission.split('.').pop(); return <label key={permission} className="flex min-h-9 cursor-pointer items-center gap-2 rounded-md px-2 text-sm hover:bg-[var(--app-panel)]"><input type="checkbox" checked={selected.includes(permission)} onChange={() => onToggle(permission)} /><span>{actionLabels[action] || action}</span><code className="ml-auto text-[10px] text-[var(--text-muted)]">{permission}</code></label>; })}</div></fieldset>; })}</div></div>; }
export function RolesPage() {
  const [roles, setRoles] = useState([]); const [groups, setGroups] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(false); const [open, setOpen] = useState(false); const [confirm, setConfirm] = useState(null); const [message, setMessage] = useState('');
  async function load() { const [roleResponse, permissionResponse] = await Promise.all([api.get('/admin/roles'), api.get('/permissions')]); setRoles(roleResponse.data.data || []); setGroups(permissionResponse.data.data || []); }
  useEffect(() => { load().catch((error) => setMessage(apiErrorMessage(error))); }, []);
  function edit(role) { setForm({ name: role.name, description: role.description || '', permissions: role.permissions || [], libraryAccess: role.libraryAccess || [] }); setEditing(role); setOpen(true); }
  function toggle(permission) { setForm((current) => ({ ...current, permissions: current.permissions.includes(permission) ? current.permissions.filter((item) => item !== permission) : [...current.permissions, permission] })); }
  async function save(event) { event.preventDefault(); try { const response = editing ? await api.patch(`/admin/roles/${editing.id}`, form) : await api.post('/admin/roles', form); setOpen(false); setEditing(false); setForm(blank); setRoles((current) => editing ? current.map((role) => role.id === response.data.data.id ? response.data.data : role) : [...current, response.data.data]); } catch (error) { setMessage(apiErrorMessage(error)); } }
  async function remove() { try { await api.delete(`/admin/roles/${confirm.id}`, { data: { replacementRoleId: 'role-reader' } }); setConfirm(null); await load(); } catch (error) { setMessage(apiErrorMessage(error)); } }
  const columns = [{ key: 'name', label: 'Role', width: '1.2fr', render: (role) => <div><span className="font-semibold">{role.name}</span>{role.isSystem && <StatusBadge tone="info">Sistema</StatusBadge>}</div> }, { key: 'description', label: 'Descrição', width: '1.6fr', render: (role) => <span className="truncate text-sm text-[var(--text-muted)]">{role.description || '—'}</span> }, { key: 'users', label: 'Usuários', width: 'auto', render: (role) => role.userCount }, { key: 'permissions', label: 'Permissões', width: 'auto', render: (role) => role.isSystem ? 'Todas' : role.permissions.length }, { key: 'actions', label: 'Ações', width: 'auto', align: 'right', render: (role) => <div className="flex gap-1"><button type="button" onClick={() => edit(role)} className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--app-border)]" aria-label="Editar role"><Pencil className="h-4 w-4" /></button>{!role.isSystem && <button type="button" onClick={() => setConfirm(role)} className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--app-border)] text-[var(--danger)]" aria-label="Excluir role"><Trash2 className="h-4 w-4" /></button>}</div> }];
  return <AdminPage title="Roles" description="Defina permissões e acesso às bibliotecas para cada função." actions={<button type="button" onClick={() => { setForm(blank); setEditing(false); setOpen(true); }} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[var(--brand-primary)] px-4 text-sm font-semibold text-[var(--accent-foreground)]"><Plus className="h-4 w-4" />Nova role</button>}><AdminDataGrid columns={columns} rows={roles} loading={false} error={message} empty="Nenhuma role configurada." /><Dialog.Root open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90dvh] w-[min(94vw,820px)] overflow-y-auto"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{editing ? 'Editar role' : 'Nova role'}</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Uma role reúne permissões para simplificar o controle de acesso.</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Fechar" className="grid h-9 w-9 place-items-center rounded-lg hover:bg-[var(--app-bg)]"><X /></button></div><form onSubmit={save} className="mt-5 grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Nome<input className={inputClass} value={form.name} disabled={Boolean(editing?.isSystem)} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label className="text-sm font-medium">Descrição<textarea className={inputClass} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div>{editing?.isSystem ? <p className="text-sm text-[var(--text-muted)]">Roles do sistema são protegidas e possuem acesso predefinido.</p> : <div><p className="text-sm font-semibold">Permissões por área</p><PermissionGroups groups={groups} selected={form.permissions} onToggle={toggle} /></div>}<button className="min-h-11 rounded-xl bg-[var(--brand-primary)] px-4 text-sm font-semibold text-[var(--accent-foreground)]">Salvar role</button></form></DialogContent></Dialog.Root><Dialog.Root open={Boolean(confirm)} onOpenChange={(value) => !value && setConfirm(null)}><DialogContent className="w-[min(92vw,420px)]"><h2 className="text-xl font-semibold">Excluir role?</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Usuários vinculados serão movidos para Reader.</p><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setConfirm(null)} className="rounded-xl border px-4 py-2">Cancelar</button><button type="button" onClick={remove} className="rounded-xl bg-[var(--danger)] px-4 py-2 font-semibold text-white">Excluir</button></div></DialogContent></Dialog.Root></AdminPage>;
}
export { RolesPage as ProfilesPage };
