import { useEffect, useState } from 'react';
import { api, apiErrorMessage } from '../../../lib/api.js';
import { useLocale } from '../../../context/LocaleContext.jsx';
import { AdminPage, SettingsGroup, StatusLine } from '../components/AdminPrimitives.jsx';
import AdminTabs from '../components/AdminTabs.jsx';

const fallback = { authentication: { maxLoginAttempts: 10, loginWindowSeconds: 900, lockoutSeconds: 900, strongPassword: false, minPasswordLength: 4, requireUppercase: false, requireLowercase: false, requireNumber: false, requireSpecial: false, requirePasswordChange: false, passwordHistoryEnabled: false, passwordHistoryCount: 5, passwordExpirationEnabled: false, passwordExpirationDays: 90, passwordExpirationWarningDays: 7 }, sessions: { sessionSeconds: 86400 }, rateLimit: { enabled: false, store: 'memory', profiles: { login: { max: 10, windowSeconds: 900 }, api: { max: 300, windowSeconds: 60 } } }, cookies: { secure: false, sameSite: 'lax' }, headers: {}, audit: { enabled: true, retentionDays: 90 } };
function NumberField({ value, onChange, min = 0, max = 999999 }) { return <input type="number" min={min} max={max} value={value ?? ''} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 min-h-10 w-full max-w-[9rem] rounded-lg border border-[var(--app-border)] bg-[var(--app-panel)] px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]/35" />; }
function Toggle({ label, checked, onChange, disabled = false }) { return <label className={`flex min-h-10 items-center gap-2 text-sm ${disabled ? 'opacity-50' : ''}`}><input type="checkbox" checked={Boolean(checked)} onChange={(event) => onChange(event.target.checked)} disabled={disabled} />{label}</label>; }
function SecurityField({ label, children }) { return <div><p className="text-sm font-medium">{label}</p>{children}</div>; }
export default function SecurityTabbedPage() {
  const { t } = useLocale(); const [data, setData] = useState(null); const [draft, setDraft] = useState(null); const [status, setStatus] = useState('');
  useEffect(() => { api.get('/admin/security').then(({ data: response }) => { const value = { ...fallback, ...(response.data?.config || {}) }; value.authentication = { ...fallback.authentication, ...(value.authentication || {}) }; setData(response.data); setDraft(value); }).catch((error) => setStatus(apiErrorMessage(error))); }, []);
  const update = (section, key, value) => setDraft((current) => ({ ...current, [section]: { ...current[section], [key]: value } }));
  const save = async () => { setStatus('saving'); try { const a = draft.authentication; const response = await api.patch('/admin/security/config', { expectedVersion: data.settingsVersion, authentication: a, sessions: { sessionSeconds: draft.sessions.sessionSeconds }, rateLimit: draft.rateLimit, cookies: draft.cookies, reader: { externalContent: draft.reader?.externalContent || 'block' } }); setDraft(response.data.data.config || response.data.data); setStatus('saved'); } catch (error) { setStatus(apiErrorMessage(error)); } };
  if (!draft) return <AdminPage title={t('admin.sections.security')} description={t('admin.descriptions.security')}><p className="text-sm text-[var(--text-muted)]">{status || t('common.loading')}</p></AdminPage>;
  const a = draft.authentication; const setA = (key, value) => update('authentication', key, value);
  return <AdminPage title={t('admin.sections.security')} description="Gerencie políticas de autenticação e proteção da aplicação." actions={<button type="button" onClick={save} disabled={status === 'saving'} className="min-h-11 rounded-xl bg-[var(--brand-primary)] px-5 text-sm font-semibold text-[var(--accent-foreground)] disabled:opacity-50">{status === 'saving' ? 'Salvando…' : 'Salvar alterações'}</button>}>
    {status === 'saved' && <p role="status" className="mb-6 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-200">Configurações salvas.</p>}{status && status !== 'saved' && status !== 'saving' && <p role="alert" className="mb-6 text-sm text-[var(--danger)]">{status}</p>}
    <AdminTabs tabs={[['overview','Visão geral'],['passwords','Senhas'],['sessions','Sessões'],['rateLimit','Rate limit'],['cookies','Cookies'],['access','Acesso']]}>{(tab) => <>
      {tab === 'overview' && <SettingsGroup title="Visão geral" description="Resumo das proteções ativas nesta instalação."><div className="grid gap-x-8 sm:grid-cols-2"><StatusLine label="Política de senha" value={a.strongPassword ? 'Reforçada' : 'Básica'} tone="good" /><StatusLine label="Expiração" value={a.passwordExpirationEnabled ? `${a.passwordExpirationDays} dias` : 'Desativada'} /><StatusLine label="Rate limit" value={draft.rateLimit.enabled ? 'Ativo' : 'Desativado'} /><StatusLine label="Cookies seguros" value={draft.cookies.secure ? 'Ativo' : 'Desativado'} /></div></SettingsGroup>}
      {tab === 'passwords' && <div className="space-y-5"><SettingsGroup title="Política de senha" description="Requisitos aplicados durante criação, alteração e recuperação de senhas."><div className="grid gap-5 sm:grid-cols-2"><SecurityField label="Política forte"><Toggle label="Ativar requisitos adicionais" checked={a.strongPassword} onChange={(v) => setA('strongPassword', v)} /></SecurityField><SecurityField label="Comprimento mínimo"><NumberField value={a.minPasswordLength} min={4} max={128} onChange={(v) => setA('minPasswordLength', v)} /></SecurityField></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['requireUppercase','Uma letra maiúscula'],['requireLowercase','Uma letra minúscula'],['requireNumber','Um número'],['requireSpecial','Um caractere especial']].map(([key, label]) => <Toggle key={key} label={`Exigir ${label.toLowerCase()}`} checked={a[key]} disabled={!a.strongPassword} onChange={(v) => setA(key, v)} />)}</div></SettingsGroup><SettingsGroup title="Histórico e expiração" description="Controle reutilização e validade das credenciais."><div className="grid gap-5 sm:grid-cols-2"><SecurityField label="Histórico"><Toggle label="Impedir reutilização" checked={a.passwordHistoryEnabled} onChange={(v) => setA('passwordHistoryEnabled', v)} /></SecurityField><SecurityField label="Senhas lembradas"><NumberField value={a.passwordHistoryCount} min={1} max={24} onChange={(v) => setA('passwordHistoryCount', v)} /></SecurityField><SecurityField label="Expiração"><Toggle label="Exigir troca periódica" checked={a.passwordExpirationEnabled} onChange={(v) => setA('passwordExpirationEnabled', v)} /></SecurityField><SecurityField label="Validade (dias)"><NumberField value={a.passwordExpirationDays} min={1} max={365} onChange={(v) => setA('passwordExpirationDays', v)} /></SecurityField><SecurityField label="Aviso antes (dias)"><NumberField value={a.passwordExpirationWarningDays} min={0} max={30} onChange={(v) => setA('passwordExpirationWarningDays', v)} /></SecurityField></div></SettingsGroup></div>}
      {tab === 'sessions' && <SettingsGroup title="Sessões" description="Duração e comportamento das sessões de acesso."><SecurityField label="Duração da sessão"><NumberField value={draft.sessions.sessionSeconds} min={60} max={2592000} onChange={(v) => update('sessions', 'sessionSeconds', v)} /></SecurityField></SettingsGroup>}
      {tab === 'rateLimit' && <SettingsGroup title="Rate limit" description={`Limites de requisições. Armazenamento atual: ${draft.rateLimit.store || 'memory'}.`}><Toggle label="Ativar rate limit" checked={draft.rateLimit.enabled} onChange={(v) => update('rateLimit', 'enabled', v)} /><div className="mt-5 grid gap-5 sm:grid-cols-2">{Object.entries(draft.rateLimit.profiles || {}).map(([key, value]) => <div key={key} className="rounded-xl border border-[var(--app-border)] p-4"><h3 className="font-semibold capitalize">{key === 'api' ? 'API' : 'Login'}</h3><SecurityField label="Máximo"><NumberField value={value.max} min={1} onChange={(v) => update('rateLimit', 'profiles', { ...draft.rateLimit.profiles, [key]: { ...value, max: v } })} /></SecurityField></div>)}</div></SettingsGroup>}
      {tab === 'cookies' && <SettingsGroup title="Cookies de sessão" description="Flags de proteção aplicadas aos cookies de autenticação."><div className="grid gap-5 sm:grid-cols-2"><Toggle label="Secure — somente HTTPS" checked={draft.cookies.secure} onChange={(v) => update('cookies', 'secure', v)} /><SecurityField label="SameSite"><select value={draft.cookies.sameSite} onChange={(event) => update('cookies', 'sameSite', event.target.value)} className="mt-2 min-h-10 w-full max-w-[12rem] rounded-lg border border-[var(--app-border)] bg-[var(--app-panel)] px-3 text-sm"><option value="lax">Lax</option><option value="strict">Strict</option><option value="none">None</option></select></SecurityField><StatusLine label="HttpOnly" value="Ativo e gerenciado pelo Araru" tone="good" /></div></SettingsGroup>}
      {tab === 'access' && <SettingsGroup title="Acesso" description="Proteções contra tentativas de login e comportamento inicial das contas."><div className="grid gap-5 sm:grid-cols-2"><SecurityField label="Máximo de tentativas"><NumberField value={a.maxLoginAttempts} min={1} max={100} onChange={(v) => setA('maxLoginAttempts', v)} /></SecurityField><SecurityField label="Janela de login (segundos)"><NumberField value={a.loginWindowSeconds} min={10} onChange={(v) => setA('loginWindowSeconds', v)} /></SecurityField><SecurityField label="Bloqueio (segundos)"><NumberField value={a.lockoutSeconds} min={0} onChange={(v) => setA('lockoutSeconds', v)} /></SecurityField><Toggle label="Exigir troca no primeiro login" checked={a.requirePasswordChange} onChange={(v) => setA('requirePasswordChange', v)} /></div></SettingsGroup>}
    </>}</AdminTabs>
  </AdminPage>;
}
